apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: prod
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: nginx
          image: ressafri/nginx:v0.1.2
          ports:
            - containerPort: 80

